id = "WebfishingRichPresence"
description = "Adds Discord Rich Presence to WEBFISHING"
version = "1.1.0"
homepage = "https://github.com/NotNite/WebfishingRichPresence"
author = "NotNite"

icon = "icon.png"
readme = "README.md"

extra_files = ["librpc/target/release/librpc.dll"]

[project]
csharp = "./WebfishingRichPresence/WebfishingRichPresence.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"
